### ISSUE TITLE
Correct missing internal link

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/my-little-rainbow#25]
The link at line 4 of README.md is supposed to link to an anchor on the same page at line 53. As it stands, this link on line 4 only opens another copy of this same page. It does not jump down the page to where it should, which is at the subtitle "Making a Rainbow".

**Comment by pletcher** [comment]
@becky000 I'm not able to reproduce -- the link works as expected for me. What browser are you using?

**Comment by ghost** [comment]
I'm using Chrome on Windows 10 pc. The link opens a new window with a duplicate page instead of jumping down the page to the anchor.

**Comment by pletcher** [comment]
Hm, I'm using Chrome on OS X and the link works as expected. Is your browser set to automatically open links in a new tab?

**Comment by ghost** [comment]
It does, but when I encounter page up/top/type of internal links they work in other places. I just updated Chrome, and it still opens a duplicate page, it just shows it as having the #making-a-rainbow at the end of the url.

**Comment by pletcher** [comment]
Ah, got it. This is happening on Learn.co, right? (Sorry, I was testing on GitHub -- my bad.)

**Comment by ghost** [comment]
:) Yes it's from the Learn.co site.

**Comment by pletcher** [comment]
Cool, I'll file a bug there -- can't fix it in this repo, unfortunately :( Thanks for raising this issue, though!
