### ISSUE TITLE
Error in My Little Rainbow Lesson Text

### ISSUE THREAD

**Issue by YogiBogie** [learn-co-curriculum/my-little-rainbow#33]
Half way down the lesson there is a list of all the HEX digit values, the listing for HEX is wrong.  It Show:

  Decimal Numbers:      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
  Hexadecimal Numbers:  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, a,  b,  c,  d,  e,  f,  10

But the '10' after the 'f' value shouldn't be there.  The error occurs because the Decimal Numbers shown actually show 17 digits, and so when trying to match the number of digits for Hex Numbers the 10 was mistakenly added.  The correct Decimal Numbers should be 0-15 (16 digits total) and the '10' should be deleted from the Hexadecimal Numbers.  So basically:

  Decimal Numbers:      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
  Hexadecimal Numbers:  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, a,  b,  c,  d,  e,  f

**Comment by gj** [comment]
Hi @YogiBogie !

10 is the decimal number 16 in hexadecimal. 🙂
