### ISSUE TITLE
order of Hex numbers

### ISSUE THREAD

**Issue by vsparrow** [learn-co-curriculum/my-little-rainbow#35]
listed as 
Hexadecimal Numbers:  0, 1, 2, 3, 4, 5, 6, 7, 8, 9,  a,  b,  c,  d,  e,  f, 10

Hex should be 0-9,a-f    no 10 included

**Comment by gj** [comment]
Hi @vsparrow !

`10` is a perfectly valid hexadecimal number — it's the equivalent of the decimal number `16`. Hope that clears things up! 🙂
